### ISSUE TITLE
error during installation rakudo-2020.05.1 on windows 10

### ISSUE THREAD

**Issue by interlab** [Raku/nqp#628]
windows 10, perl v5.30.0

`perl Configure.pl --gen-moar --gen-nqp --backends=moar`

![raku-win-fail](https://user-images.githubusercontent.com/2246621/81665751-c2cd9d80-9449-11ea-9635-60970800443d.png)

**Comment by Altai-man** [comment]
Hmm, this even looks to me like a moar issue, but I can't transfer ticket there.
Seems it was introduced in https://github.com/MoarVM/MoarVM/commit/8f2d0d7818e0e987d567b91dd1ef55730a52814d#diff-beff3d4230b1ad1b250922477a3e1de5
So here since 2020.01.
What I wonder about is why did appveyor not report this when building on windows.

**Comment by Prince213** [comment]
This commit is included in 2020.05.1 right? I'm using Visual C++ and don't have this problem.

**Comment by Altai-man** [comment]
It is included.
@interlab can you please provide some more info on how do you compile it?

**Comment by interlab** [comment]
I had an old version of gcc running. it was taken from the haskell folder for 2014.2.0.0. I removed this path from Path and now gcc is taken from perl 5.30.0.2.
Thanks all for helping me!

---

```
perl Configure.pl --gen-moar --gen-nqp --backends=moar
gmake
gmake test
gmake install

C:\rakudo2020051\rakudo-m.exe -e "$*RAKU.compiler.version.say"
```
> v2020.05.1

why there is no file **raku.exe**?

**Comment by Prince213** [comment]
There should be one, but you can always copy bin/rakudo.exe and rename it to raku.exe
