### ISSUE TITLE
Need a make target to aid debugging

### ISSUE THREAD

**Issue by tbrowder** [Raku/nqp#631]
When working on source code and "make" fails, build code is removed and bug finding is difficult because the backtrace doesn't always point back to the original source code.

If this route were taken I would call the target "debug", e.g.,

    $ make debug

**Comment by vrurg** [comment]
Could you please elaborate on this? As I remember, there is no explicit remove on any kind of failure. Anything auto-generated stays intact until `make clean`.

**Comment by tbrowder** [comment]
The most recent failure was the one I saw in my issue #632. The build files could not be found until I changed the Makefile and replaced

    RM_*   = rm...

with

    RM_*    =

**Comment by vrurg** [comment]
`RM_` are only used by:

- `clean` targets
- runner compilation where it first removes the target and then compiles over it. Not generally needed, but migrated from the old Makefile and perhaps added on purpose. Doesn't harm either.

#632 is about a `.nqp`, thus it cannot be related to a runner. 

So far I suspect two things: either a script is involved which implicitly invokes overlooked `make clean`; what you actually look for is _gen/<backend>/stageN_ directories. Again, considering #632, the problem is about _src/HLL/sprintf.nqp_. It ends up combined into `$(M_HLL_COMBINED_STAGE<N>) which is _gen/<backend>/stageN/NQPHLL.nqp_.

The latter looks very likely because the error messages says exactly that:

```
   at gen/moar/stage2/NQPHLL.nqp:1026  (src/vm/moar/stage0/NQPHLL.moarvm:panic)
```

**Comment by tbrowder** [comment]
Exactly. And, until I modified the Makefile, it was removed after the failure.

**Comment by vrurg** [comment]
I have no idea what you really do to make it removed! I took my current copy of NQP as was cloned by Rakudo build. Went into _src/HLL/sprintf.nqp_ and made exactly the change you did. I got exactly the error message you've got. Then I do `vim gen/moar/stage1/NQPHLL.nqp`, go to the line 3039 and see something like this in my vim window:

```
     3038                 || <.panic("'" ~ nqp::substr(self.orig,1) ~ "' is not valid in sprintf format sequence '" ~ self.orig ~ "'", nqp:
     3039             > ]
```

So, _NQPHLL.nqp_ do remain in place after a failed build. 

Please, do step-by-step verification of your build process. Invoke `make` with `VERBOSE_BUILD=1` to see what exactly happens during the build. Because the problem is unreproducible otherwise.

**Comment by tbrowder** [comment]
Okay, I'm a dummy. The error message said "stage2" and that's where I saw the empty dir.

**Comment by tbrowder** [comment]
We might add some info to the docs, but I can close this issue.

**Comment by vrurg** [comment]
> Okay, I'm a dummy. The error message said "stage2" and that's where I saw the empty dir.

A few minutes ago I considered this possibility. :) The confusion comes from the point that first stage NQP is compiled by second stage binary which apparently would report `stage2` dir in its backtrace.

What kind of info do you want to add to the docs?

**Comment by tbrowder** [comment]
I'll have to think about it.

NOTE: I'm now having the same problem with Rakudo!!
